FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

WORKDIR /app
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev \
    git curl build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN ln -sf python3 /usr/bin/python

COPY pyproject.toml /app/pyproject.toml
RUN pip install --no-cache-dir poetry==1.8.4 && poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

COPY src /app/src
COPY README.md /app/README.md

CMD ["celery", "-A", "src.scheduler:celery", "worker", "-l", "INFO", "--concurrency=1"]
